theme = "ananke"
baseURL = "https://blog.devies.se"
title = "Devies Tech Culture Business Blog"
googleAnalytics = "G-72VEGX2X3B"

[params]
  site_logo = "/logo.png"
  favicon = "favicon.ico"
  custom_css = ["custom.css"]
  recent_posts_number = 6
[markup.goldmark.renderer] 
  unsafe = true

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/deviesgbg/"

[[params.ananke_socials]]
name = "github"
url = "https://www.github.com/deviesdevelopment/"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/company/deviesdevelopment"
