theme = "ananke"
baseURL = "https://deviesdevelopment.github.io/blog"
title = "Devies Tech Culture Business Blog"
googleAnalytics = "G-72VEGX2X3B"

[params]
  site_logo = "/blog/logo.png"
  favicon = "favicon.ico"
  custom_css = ["custom.css"]
[markup.goldmark.renderer] 
  unsafe = true
